In [17]:
from bs4 import BeautifulSoup
import pandas as pd 
import requests

In [18]:
# page = 1

# while page <= 50:   # total pages = 50
#     URL = f"https://books.toscrape.com/catalogue/page-{page}.html"
#     print(URL)
#     page += 1

In [19]:
# res = requests.get(URL)

In [20]:
# with open("data2.html",'w',encoding='utf-8') as f :
#     f.write(res.text)

In [21]:
# with open("data2.html",'r',encoding='utf-8') as f :
#     content = f.read()

# soup = BeautifulSoup(content,'html.parser')

In [22]:
# soup.find_all('h3')

In [23]:
# raw_title = soup.find_all('h3')
# title = []
# for t in raw_title:
#     title.append(t.get_text(strip=True))

In [24]:
# title

In [25]:

# price = []
# for p in raw_title:
#     price.append(p.find_next('p').get_text(strip=True))

In [26]:
# price

In [27]:
# rating = []
# for r in raw_title:
#     print(r.find('p',class_="star-rating"))

In [28]:
# ratings = []

# rating_map = {
#     "One": 1,
#     "Two": 2,
#     "Three": 3,
#     "Four": 4,
#     "Five": 5
# }

# rate = soup.find_all('article', class_="product_pod")

# for r in rate:
#     out = r.find('p', class_="star-rating")["class"][1]
#     ratings.append(rating_map[out])

# print(ratings)

In [29]:
# book_detail = []

# for t,p,r in zip(title,price,ratings):
#     book_detail.append([t,p,r])

In [30]:
# book_detail

In [36]:
book_detail = []

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

for page in range(1, 51):   # 1 → 50
    URL = f"https://books.toscrape.com/catalogue/page-{page}.html"
    print("Scraping:", URL)
    res = requests.get(URL)
    with open("data2.html",'w',encoding='utf-8') as f :
        f.write(res.text)

    with open("data2.html",'r',encoding='utf-8') as f :
        content = f.read()

    soup = BeautifulSoup(content,'html.parser')
    raw_title = soup.find_all('h3')
    title = []
    for t in raw_title:
        title.append(t.get_text(strip=True))
    
    price = []
    for p in raw_title:
        price.append(p.find_next('p').get_text(strip=True))


    rate = soup.find_all('article', class_="product_pod")
    ratings =[]

    for r in rate:
        out = r.find('p', class_="star-rating")["class"][1]
        ratings.append(rating_map[out])

    book_detail = []

    for t,p,r in zip(title,price,ratings):
        book_detail.append([t,p,r])

    df = pd.DataFrame(book_detail,columns=["Title","Price","Rating"])
    df.to_csv(
    'Save2.csv',
    mode="a",          # append
    index=False,
    header=False       # don't repeat column names
    )

Scraping: https://books.toscrape.com/catalogue/page-1.html
Scraping: https://books.toscrape.com/catalogue/page-2.html
Scraping: https://books.toscrape.com/catalogue/page-3.html
Scraping: https://books.toscrape.com/catalogue/page-4.html
Scraping: https://books.toscrape.com/catalogue/page-5.html
Scraping: https://books.toscrape.com/catalogue/page-6.html
Scraping: https://books.toscrape.com/catalogue/page-7.html
Scraping: https://books.toscrape.com/catalogue/page-8.html
Scraping: https://books.toscrape.com/catalogue/page-9.html
Scraping: https://books.toscrape.com/catalogue/page-10.html
Scraping: https://books.toscrape.com/catalogue/page-11.html
Scraping: https://books.toscrape.com/catalogue/page-12.html
Scraping: https://books.toscrape.com/catalogue/page-13.html
Scraping: https://books.toscrape.com/catalogue/page-14.html
Scraping: https://books.toscrape.com/catalogue/page-15.html
Scraping: https://books.toscrape.com/catalogue/page-16.html
Scraping: https://books.toscrape.com/catalogue/page-17.html
Scraping: https://books.toscrape.com/catalogue/page-18.html
Scraping: https://books.toscrape.com/catalogue/page-19.html
Scraping: https://books.toscrape.com/catalogue/page-20.html
Scraping: https://books.toscrape.com/catalogue/page-21.html
Scraping: https://books.toscrape.com/catalogue/page-22.html
Scraping: https://books.toscrape.com/catalogue/page-23.html
Scraping: https://books.toscrape.com/catalogue/page-24.html
Scraping: https://books.toscrape.com/catalogue/page-25.html
Scraping: https://books.toscrape.com/catalogue/page-26.html
Scraping: https://books.toscrape.com/catalogue/page-27.html
Scraping: https://books.toscrape.com/catalogue/page-28.html
Scraping: https://books.toscrape.com/catalogue/page-29.html
Scraping: https://books.toscrape.com/catalogue/page-30.html
Scraping: https://books.toscrape.com/catalogue/page-31.html
Scraping: https://books.toscrape.com/catalogue/page-32.html
Scraping: https://books.toscrape.com/catalogue/page-33.html
Scraping: https://books.toscrape.com/catalogue/page-34.html
Scraping: https://books.toscrape.com/catalogue/page-35.html
Scraping: https://books.toscrape.com/catalogue/page-36.html
Scraping: https://books.toscrape.com/catalogue/page-37.html
Scraping: https://books.toscrape.com/catalogue/page-38.html
Scraping: https://books.toscrape.com/catalogue/page-39.html
Scraping: https://books.toscrape.com/catalogue/page-40.html
Scraping: https://books.toscrape.com/catalogue/page-41.html
Scraping: https://books.toscrape.com/catalogue/page-42.html
Scraping: https://books.toscrape.com/catalogue/page-43.html
Scraping: https://books.toscrape.com/catalogue/page-44.html
Scraping: https://books.toscrape.com/catalogue/page-45.html
Scraping: https://books.toscrape.com/catalogue/page-46.html
Scraping: https://books.toscrape.com/catalogue/page-47.html
Scraping: https://books.toscrape.com/catalogue/page-48.html
Scraping: https://books.toscrape.com/catalogue/page-49.html
Scraping: https://books.toscrape.com/catalogue/page-50.html

In [46]:
df  
# df1.info()
print(df.columns)

Index(['Title', 'Price', 'Rating'], dtype='object')

In [ ]:
df =pd.read_csv('Save2.csv')

                   A Light in the ...  Â£51.77  3
0                  Tipping the Velvet  Â£53.74  1
1                          Soumission  Â£50.10  1
2                       Sharp Objects  Â£47.82  4
3        Sapiens: A Brief History ...  Â£54.23  5
4                     The Requiem Red  Â£22.65  1
..                                ...      ... ..
994  Alice in Wonderland (Alice's ...  Â£55.53  1
995    Ajin: Demi-Human, Volume 1 ...  Â£57.06  4
996         A Spy's Devotion (The ...  Â£16.97  5
997           1st to Die (Women's ...  Â£53.98  1
998           1,000 Places to See ...  Â£26.08  5

[999 rows x 3 columns]

In [56]:
df.columns =["Title","Price","Rating"]

In [57]:
df

                                Title    Price  Rating
0                  Tipping the Velvet  Â£53.74       1
1                          Soumission  Â£50.10       1
2                       Sharp Objects  Â£47.82       4
3        Sapiens: A Brief History ...  Â£54.23       5
4                     The Requiem Red  Â£22.65       1
..                                ...      ...     ...
994  Alice in Wonderland (Alice's ...  Â£55.53       1
995    Ajin: Demi-Human, Volume 1 ...  Â£57.06       4
996         A Spy's Devotion (The ...  Â£16.97       5
997           1st to Die (Women's ...  Â£53.98       1
998           1,000 Places to See ...  Â£26.08       5

[999 rows x 3 columns]

In [63]:
df["Price"] = df["Price"].str.replace("Â£", "", regex=False)
df

                                Title   Price  Rating
0                  Tipping the Velvet  Â53.74       1
1                          Soumission  Â50.10       1
2                       Sharp Objects  Â47.82       4
3        Sapiens: A Brief History ...  Â54.23       5
4                     The Requiem Red  Â22.65       1
..                                ...     ...     ...
994  Alice in Wonderland (Alice's ...  Â55.53       1
995    Ajin: Demi-Human, Volume 1 ...  Â57.06       4
996         A Spy's Devotion (The ...  Â16.97       5
997           1st to Die (Women's ...  Â53.98       1
998           1,000 Places to See ...  Â26.08       5

[999 rows x 3 columns]

### SQL