In [2]:
import requests
import pandas as pd

In [3]:
URL = 'https://stephen-king-api.onrender.com/api/books'

In [4]:
r = requests.get(URL)

In [5]:
r.status_code
json_data = r.json()
json_data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [6]:
df = pd.json_normalize(json_data["data"])
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [7]:
df[['id','Title','Year']].sort_values('Year',ascending=False)

    id          Title  Year
61  62          Later  2021
62  63  Billy Summers  2021
60  61  The Institute  2019
58  59   The Outsider  2018
59  60      Elevation  2018
..  ..            ...   ...
4    5      The Stand  1978
3    4           Rage  1977
2    3    The Shining  1977
1    2    Salem's Lot  1975
0    1         Carrie  1974

[63 rows x 3 columns]

In [8]:
# covcid api
url_2 = 'https://api.fda.gov/drug/event.json?limit=1'
data = requests.get(url_2)
res = data.json()
res

{'meta': {'disclaimer': 'Do not rely on openFDA to make decisions regarding medical care. While we make every effort to ensure that data is accurate, you should assume all results are unvalidated. We may limit or otherwise restrict your access to the API in line with our Terms of Service.',
  'terms': 'https://open.fda.gov/terms/',
  'license': 'https://open.fda.gov/license/',
  'last_updated': '2025-10-30',
  'results': {'skip': 0, 'limit': 1, 'total': 19684585}},
 'results': [{'safetyreportid': '5801206-7',
   'transmissiondateformat': '102',
   'transmissiondate': '20090109',
   'serious': '1',
   'seriousnessdeath': '1',
   'receivedateformat': '102',
   'receivedate': '20080707',
   'receiptdateformat': '102',
   'receiptdate': '20080625',
   'fulfillexpeditecriteria': '1',
   'companynumb': 'JACAN16471',
   'primarysource': {'reportercountry': 'CANADA', 'qualification': '3'},
   'sender': {'senderorganization': 'FDA-Public Use'},
   'receiver': None,
   'patient': {'patientonsetage': '26',
    'patientonsetageunit': '801',
    'patientsex': '1',
    'patientdeath': {'patientdeathdateformat': None, 'patientdeathdate': None},
    'reaction': [{'reactionmeddrapt': 'DRUG ADMINISTRATION ERROR'},
     {'reactionmeddrapt': 'OVERDOSE'}],
    'drug': [{'drugcharacterization': '1',
      'medicinalproduct': 'DURAGESIC-100',
      'drugauthorizationnumb': '019813',
      'drugadministrationroute': '041',
      'drugindication': 'DRUG ABUSE'}]}}]}

In [9]:
df = pd.json_normalize(res['results'])
df

,safetyreportid,transmissiondateformat,transmissiondate,serious,seriousnessdeath,receivedateformat,receivedate,receiptdateformat,receiptdate,fulfillexpeditecriteria,...,primarysource.reportercountry,primarysource.qualification,sender.senderorganization,patient.patientonsetage,patient.patientonsetageunit,patient.patientsex,patient.patientdeath.patientdeathdateformat,patient.patientdeath.patientdeathdate,patient.reaction,patient.drug
0,5801206-7,102,20090109,1,1,102,20080707,102,20080625,1,...,CANADA,3,FDA-Public Use,26,801,1,None,None,[{'reactionmeddrapt': 'DRUG ADMINISTRATION ERR...,"[{'drugcharacterization': '1', 'medicinalprodu..."

web scrapping and save

In [10]:
URL = 'https://books.toscrape.com/catalogue/category/books/romance_8/index.html'
res =requests.get(URL)

In [11]:
print(res.status_code)
print(res.text)

200


<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    Romance |
     Books to Scrape - Sandbox

</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="

" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="../../../../static/oscar/favicon.ico" />






        <link rel="stylesheet" type="text/css" href="../../../../static/oscar/css/styles.css" />

    <link rel="stylesheet" href="../../../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" type="text/css" href="../../../../static/oscar/css/datetimepicker.css" />












    </head>

    <body id="default" class="default">




    <header class="header container-fluid">
        <div class="page_inner">
            <div class="row">
                <div class="col-sm-8 h1"><a href="../../../../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>


            </div>
        </div>
    </header>



<div class="container-fluid page">
    <div class="page_inner">

    <ul class="breadcrumb">
        <li>
            <a href="../../../../index.html">Home</a>
        </li>

            <li>
                <a href="../../books_1/index.html">Books</a>
            </li>

        <li class="active">Romance</li>
    </ul>

        <div class="row">

            <aside class="sidebar col-sm-4 col-md-3">

                <div id="promotions_left">

                </div>




        <div class="side_categories">
            <ul class="nav nav-list">

                    <li>
                        <a href="../../books_1/index.html">

                                Books

                        </a>

                        <ul>


                    <li>
                        <a href="../travel_2/index.html">

                                Travel

                        </a>

                        </li>


                    <li>
                        <a href="../mystery_3/index.html">

                                Mystery

                        </a>

                        </li>


                    <li>
                        <a href="../historical-fiction_4/index.html">

                                Historical Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../sequential-art_5/index.html">

                                Sequential Art

                        </a>

                        </li>


                    <li>
                        <a href="../classics_6/index.html">

                                Classics

                        </a>

                        </li>


                    <li>
                        <a href="../philosophy_7/index.html">

                                Philosophy

                        </a>

                        </li>


                    <li>
                        <a href="index.html">

                                <strong>Romance</strong>

                        </a>

                        </li>


                    <li>
                        <a href="../womens-fiction_9/index.html">

                                Womens Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../fiction_10/index.html">

                                Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../childrens_11/index.html">

                                Childrens

                        </a>

                        </li>


                    <li>
                        <a href="../religion_12/index.html">

                                Religion

                        </a>

                        </li>


                    <li>
                        <a href="../nonfiction_13/index.html">

                                Nonfiction

                        </a>

                        </li>


                    <li>
                        <a href="../music_14/index.html">

                                Music

                        </a>

                        </li>


                    <li>
                        <a href="../default_15/index.html">

                                Default

                        </a>

                        </li>


                    <li>
                        <a href="../science-fiction_16/index.html">

                                Science Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../sports-and-games_17/index.html">

                                Sports and Games

                        </a>

                        </li>


                    <li>
                        <a href="../add-a-comment_18/index.html">

                                Add a comment

                        </a>

                        </li>


                    <li>
                        <a href="../fantasy_19/index.html">

                                Fantasy

                        </a>

                        </li>


                    <li>
                        <a href="../new-adult_20/index.html">

                                New Adult

                        </a>

                        </li>


                    <li>
                        <a href="../young-adult_21/index.html">

                                Young Adult

                        </a>

                        </li>


                    <li>
                        <a href="../science_22/index.html">

                                Science

                        </a>

                        </li>


                    <li>
                        <a href="../poetry_23/index.html">

                                Poetry

                        </a>

                        </li>


                    <li>
                        <a href="../paranormal_24/index.html">

                                Paranormal

                        </a>

                        </li>


                    <li>
                        <a href="../art_25/index.html">

                                Art

                        </a>

                        </li>


                    <li>
                        <a href="../psychology_26/index.html">

                                Psychology

                        </a>

                        </li>


                    <li>
                        <a href="../autobiography_27/index.html">

                                Autobiography

                        </a>

                        </li>


                    <li>
                        <a href="../parenting_28/index.html">

                                Parenting

                        </a>

                        </li>


                    <li>
                        <a href="../adult-fiction_29/index.html">

                                Adult Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../humor_30/index.html">

                                Humor

                        </a>

                        </li>


                    <li>
                        <a href="../horror_31/index.html">

                                Horror

                        </a>

                        </li>


                    <li>
                        <a href="../history_32/index.html">

                                History

                        </a>

                        </li>


                    <li>
                        <a href="../food-and-drink_33/index.html">

                                Food and Drink

                        </a>

                        </li>


                    <li>
                        <a href="../christian-fiction_34/index.html">

                                Christian Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../business_35/index.html">

                                Business

                        </a>

                        </li>


                    <li>
                        <a href="../biography_36/index.html">

                                Biography

                        </a>

                        </li>


                    <li>
                        <a href="../thriller_37/index.html">

                                Thriller

                        </a>

                        </li>


                    <li>
                        <a href="../contemporary_38/index.html">

                                Contemporary

                        </a>

                        </li>


                    <li>
                        <a href="../spirituality_39/index.html">

                                Spirituality

                        </a>

                        </li>


                    <li>
                        <a href="../academic_40/index.html">

                                Academic

                        </a>

                        </li>


                    <li>
                        <a href="../self-help_41/index.html">

                                Self Help

                        </a>

                        </li>


                    <li>
                        <a href="../historical_42/index.html">

                                Historical

                        </a>

                        </li>


                    <li>
                        <a href="../christian_43/index.html">

                                Christian

                        </a>

                        </li>


                    <li>
                        <a href="../suspense_44/index.html">

                                Suspense

                        </a>

                        </li>


                    <li>
                        <a href="../short-stories_45/index.html">

                                Short Stories

                        </a>

                        </li>


                    <li>
                        <a href="../novels_46/index.html">

                                Novels

                        </a>

                        </li>


                    <li>
                        <a href="../health_47/index.html">

                                Health

                        </a>

                        </li>


                    <li>
                        <a href="../politics_48/index.html">

                                Politics

                        </a>

                        </li>


                    <li>
                        <a href="../cultural_49/index.html">

                                Cultural

                        </a>

                        </li>


                    <li>
                        <a href="../erotica_50/index.html">

                                Erotica

                        </a>

                        </li>


                    <li>
                        <a href="../crime_51/index.html">

                                Crime

                        </a>

                        </li>

                            </ul></li>


            </ul>
        </div>



            </aside>

            <div class="col-sm-8 col-md-9">

                <div class="page-header action">
                    <h1>Romance</h1>
                </div>






<div id="messages">

</div>


                <div id="promotions">

                </div>




    <form method="get" class="form-horizontal">

        <div style="display:none">


        </div>




                    <strong>35</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>

        <section>
            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>

            <div>
                <ol class="row">

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../chase-me-paris-nights-2_977/index.html"><img src="../../../../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg" alt="Chase Me (Paris Nights #2)" class="thumbnail"></a>


            </div>




                <p class="star-rating Five">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£25.27</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../black-dust_976/index.html"><img src="../../../../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg" alt="Black Dust" class="thumbnail"></a>


            </div>




                <p class="star-rating Five">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>



            <div class="product_price">








        <p class="price_color">Â£34.53</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../her-backup-boyfriend-the-sorensen-family-1_896/index.html"><img src="../../../../media/cache/1e/bb/1ebbbc3e2d3249b111033cfc40763b0b.jpg" alt="Her Backup Boyfriend (The Sorensen Family #1)" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../her-backup-boyfriend-the-sorensen-family-1_896/index.html" title="Her Backup Boyfriend (The Sorensen Family #1)">Her Backup Boyfriend (The ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£33.97</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../first-and-first-five-boroughs-3_893/index.html"><img src="../../../../media/cache/c4/d1/c4d1517cc9370e292366b6132ca9ca36.jpg" alt="First and First (Five Boroughs #3)" class="thumbnail"></a>


            </div>




                <p class="star-rating Four">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../first-and-first-five-boroughs-3_893/index.html" title="First and First (Five Boroughs #3)">First and First (Five ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£15.97</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../fifty-shades-darker-fifty-shades-2_892/index.html"><img src="../../../../media/cache/cc/bd/ccbdae9e29b3594301528fa2c876ec29.jpg" alt="Fifty Shades Darker (Fifty Shades #2)" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../fifty-shades-darker-fifty-shades-2_892/index.html" title="Fifty Shades Darker (Fifty Shades #2)">Fifty Shades Darker (Fifty ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£21.96</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../../the-wedding-dress_864/index.html"><img src="../../../../media/cache/28/99/28992d89f4abf54fba183fc8d074adf3.jpg" alt="The Wedding Dress" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../../the-wedding-dress_864/index.html" title="The Wedding Dress">The Wedding Dress</a></h3>




In [12]:
with open(r'E:\AIML_apna_college\9API\scrap.html', 'w', encoding='utf-8') as f:
    f.write(res.text)

In [13]:
from bs4 import BeautifulSoup

In [14]:

with open(r'E:\AIML_apna_college\9API\scrap.html', 'r', encoding='utf-8') as f:
    Html_content =f.read()

In [15]:
soup = BeautifulSoup(Html_content, 'html.parser')

In [21]:
all_h3 = soup.find_all('h3')
# all_h3
name = []
for h3 in all_h3:
    name.append(h3.get_text(strip=True))

name

['Chase Me (Paris Nights ...',
 'Black Dust',
 'Her Backup Boyfriend (The ...',
 'First and First (Five ...',
 'Fifty Shades Darker (Fifty ...',
 'The Wedding Dress',
 'Suddenly in Love (Lake ...',
 'Something More Than This',
 'Doing It Over (Most ...',
 'The Wedding Pact (The ...',
 'Hold Your Breath (Search ...',
 'Dirty (Dive Bar #1)',
 'Take Me Home Tonight ...',
 'Off the Hook (Fishing ...',
 "A Gentleman's Position (Society ...",
 'Sit, Stay, Love',
 "A Girl's Guide to ...",
 'The Perfect Play (Play ...',
 'Dark Lover (Black Dagger ...',
 'Changing the Game (Play ...']

In [17]:
cost = []
for h3 in all_h3:
    cost.append(h3.find_next('p').getText(strip=True))
    print(cost)

['Â£25.27']
['Â£25.27', 'Â£34.53']
['Â£25.27', 'Â£34.53', 'Â£33.97']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75', 'Â£20.90']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75', 'Â£20.90', 'Â£31.30']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75', 'Â£20.90', 'Â£31.30', 'Â£59.99']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75', 'Â£20.90', 'Â£31.30', 'Â£59.99', 'Â£12.87']
['Â£25.27', 'Â£34.53', 'Â£33.97', 'Â£15.97', 'Â£21.96', 'Â£24.12', 'Â£55.99', 'Â£16.24', 'Â£35.61', 'Â£32.61', 'Â£28.82', 'Â£40.83', 'Â£53.98', 'Â£47.67', 'Â£14.75', 'Â£20.90', 'Â£31.30', 'Â£59.99', 'Â£12.87', 'Â£13.38']

In [18]:
book_detail = []

for n, c in zip(name, cost):
    book_detail.append([n, c])

book_detail

[['Chase Me (Paris Nights ...', 'Â£25.27'],
 ['Black Dust', 'Â£34.53'],
 ['Her Backup Boyfriend (The ...', 'Â£33.97'],
 ['First and First (Five ...', 'Â£15.97'],
 ['Fifty Shades Darker (Fifty ...', 'Â£21.96'],
 ['The Wedding Dress', 'Â£24.12'],
 ['Suddenly in Love (Lake ...', 'Â£55.99'],
 ['Something More Than This', 'Â£16.24'],
 ['Doing It Over (Most ...', 'Â£35.61'],
 ['The Wedding Pact (The ...', 'Â£32.61'],
 ['Hold Your Breath (Search ...', 'Â£28.82'],
 ['Dirty (Dive Bar #1)', 'Â£40.83'],
 ['Take Me Home Tonight ...', 'Â£53.98'],
 ['Off the Hook (Fishing ...', 'Â£47.67'],
 ["A Gentleman's Position (Society ...", 'Â£14.75'],
 ['Sit, Stay, Love', 'Â£20.90'],
 ["A Girl's Guide to ...", 'Â£31.30'],
 ['The Perfect Play (Play ...', 'Â£59.99'],
 ['Dark Lover (Black Dagger ...', 'Â£12.87'],
 ['Changing the Game (Play ...', 'Â£13.38']]

In [19]:
import pandas as pd 
df = pd.DataFrame(book_detail,columns=["Title","Cost"])

In [20]:
df

                                  Title     Cost
0            Chase Me (Paris Nights ...  Â£25.27
1                            Black Dust  Â£34.53
2         Her Backup Boyfriend (The ...  Â£33.97
3             First and First (Five ...  Â£15.97
4        Fifty Shades Darker (Fifty ...  Â£21.96
5                     The Wedding Dress  Â£24.12
6            Suddenly in Love (Lake ...  Â£55.99
7              Something More Than This  Â£16.24
8               Doing It Over (Most ...  Â£35.61
9             The Wedding Pact (The ...  Â£32.61
10         Hold Your Breath (Search ...  Â£28.82
11                  Dirty (Dive Bar #1)  Â£40.83
12             Take Me Home Tonight ...  Â£53.98
13            Off the Hook (Fishing ...  Â£47.67
14  A Gentleman's Position (Society ...  Â£14.75
15                      Sit, Stay, Love  Â£20.90
16                A Girl's Guide to ...  Â£31.30
17           The Perfect Play (Play ...  Â£59.99
18         Dark Lover (Black Dagger ...  Â£12.87
19          Changing the Game (Play ...  Â£13.38